### ISSUE TITLE
Unexpected token 'export' error

### ISSUE THREAD

**Issue by Okwas** [lordicondev/lordicon#3]
When using:
1. @lordicon/react npm package
or
2. @lordicon/element and lottie-web packages
and trying to add any kind of Icon to the Player component, I get an error saying:
[vite] Internal server error: Unexpected token 'export'

Example component code below, I tried many different options to make this work:
![componentCode](https://github.com/lordicondev/lordicon/assets/23138643/a0191059-de72-4d75-aa19-9e78cc143fa6)

Project:
My project uses vite+remix combo (https://remix.run/docs/en/main/future/vite)

Full error:
09:18:25 [vite] Internal server error: Unexpected token 'export'
      at internalCompileFunction (node:internal/vm:73:18)
      at wrapSafe (node:internal/modules/cjs/loader:1153:20)
      at Module._compile (node:internal/modules/cjs/loader:1205:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
      at Module.load (node:internal/modules/cjs/loader:1091:32)
      at Module._load (node:internal/modules/cjs/loader:938:12)
      at cjsLoader (node:internal/modules/esm/translators:284:17)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:234:7)
      at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
      at async nodeImport (file:///C:/Users/demon/Desktop/projekty2023/IMB-webclient/imb-webclient/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50899:17)
      at async ssrImport (file:///C:/Users/demon/Desktop/projekty2023/IMB-webclient/imb-webclient/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50799:24)
      at async eval (C:/Users/demon/Desktop/projekty2023/IMB-webclient/imb-webclient/src/icons/city-hall-loop.tsx:4:31)
      at async instantiateModule (file:///C:/Users/demon/Desktop/projekty2023/IMB-webclient/imb-webclient/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:50861:9)
      
Full list of installed project dependencies:
![obraz](https://github.com/lordicondev/lordicon/assets/23138643/202c2a0c-ca26-4afd-9cb8-a39d33ef2985)
![obraz](https://github.com/lordicondev/lordicon/assets/23138643/e228fde1-8867-4669-b541-133217c9e7d2)

**Comment by baszczewski** [comment]
This is a problem with your project configuration.

**Comment by TheAspectDev** [comment]
i also have the same problem, how is it our problem?

**Comment by chadrogersmudbath** [comment]
I also have the same problem

**Comment by baszczewski** [comment]
> I also have the same problem

Can you provide a sample minimal project on which this will be verified?

**Comment by rafaelredigolo** [comment]
Same error here, I modified it to stay like this in the meantime
![CleanShot 2024-06-11 at 08 13 14](https://github.com/lordicondev/lordicon/assets/1581789/ba3d7b36-43af-47b0-b94e-bc7e24b4fb2c)
